### ISSUE TITLE
UI breaks randomly

### ISSUE THREAD

**Issue by Berserker66** [MauveCloud/Ic2ExpReactorPlanner#14]
The UI sometimes disappears, some elements reappear when hovering over their spot. Happens especially often when tabbing around a lot.

[Screenshot](https://i.imgur.com/E0NGHXw.png)

Tested on:
java version "1.8.0_73"
Java(TM) SE Runtime Environment (build 1.8.0_73-b02)
Java HotSpot(TM) Client VM (build 25.73-b02, mixed mode)

**Comment by MauveCloud** [comment]
If it happens randomly, that makes it very hard to track down and fix.  You might try running it from command prompt to see if that will allow it to show an error message.

**Comment by MauveCloud** [comment]
Closing, since there is insufficient information to solve this bug.  If the filer ever comes back and provides more, I can reopen it.
