### ISSUE TITLE
Tracking & display of excess heat/cooling inconsistent with actual heat throughput

### ISSUE THREAD

**Issue by lOmicronl** [MauveCloud/Ic2ExpReactorPlanner#19]
This may be a display issue only, as the simulation itself ends up correctly predicting the ingame behavior.

Detail here: http://forum.industrial-craft.net/index.php?page=Thread&postID=202990#post202990 and related

**Comment by MauveCloud** [comment]
Fixed in v2.1.5.  Calculation of excess heat/cooling did not make sense, so instead it checks for heat buildup in the reactor each tick, and displays minimum and maximum if greater than zero.
