### ISSUE TITLE
Request: EU/t yield and efficiency for unstable designs

### ISSUE THREAD

**Issue by lOmicronl** [MauveCloud/Ic2ExpReactorPlanner#20]
Right now, in order to see the EU/t and efficiency of any given fuel rod configuration, you must first build a cooling system that can survive the simulation. If you don't, then you get detailed info about how and when everything melts, but you can't see how it actually performed up until that point.

Having the report always print the efficiency and power output would help with quickly comparing various fuel rod configurations.

**Comment by MauveCloud** [comment]
Fixed in v2.1.5, though only for simple simulations.  Cooldown time is not shown for unstable designs, since that would make no sense (an exploded reactor can't cool down)
