### ISSUE TITLE
Pulsed Cycle gives an error at tick 122

### ISSUE THREAD

**Issue by Wharblar** [MauveCloud/Ic2ExpReactorPlanner#21]
### Error:
`Simulation started.
Error at reactor tick 122
java.util.IllegalFormatConversionException: d != java.lang.String [java.util.Formatter$FormatSpecifier.failConversion(Unknown Source), java.util.Formatter$FormatSpecifier.printInteger(Unknown Source), java.util.Formatter$FormatSpecifier.print(Unknown Source), java.util.Formatter.format(Unknown Source), java.util.Formatter.format(Unknown Source), java.lang.String.format(Unknown Source), Ic2ExpReactorPlanner.PulsedSimulator.doInBackground(PulsedSimulator.java:195), Ic2ExpReactorPlanner.PulsedSimulator.doInBackground(PulsedSimulator.java:14), javax.swing.SwingWorker$1.call(Unknown Source), java.util.concurrent.FutureTask.run(Unknown Source), javax.swing.SwingWorker.run(Unknown Source), java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source), java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source), java.lang.Thread.run(Unknown Source)]Simulation took 0.00 seconds.`

### Settings and Enviroment

    java -version  
    java version "1.8.0_111"  
    Java(TM) SE Runtime Environment (build 1.8.0_111-b14)  
    Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)

`EU Reactor`
Initial Component Heat: `0`
Initial Reactor Heat: `0`
Simulation Style: `Pulsed Cycle`
Code: `161616161616161616160D0C0D0C0D0C0D16160C0D0C0D0C0D0C16160D0C0D0C0D0C0D1606000D0C0D0C0D0C16060616161616161616`
Pulse Duration: `5,000,000`
Off-pulse Duration: `3`
Suspend: `18,000`
Resume: `15,000`

**Comment by MauveCloud** [comment]
Fixed in v2.1.5.1
