### ISSUE TITLE
Reprinted

### ISSUE THREAD

**Issue by 1028127425** [MauveCloud/Ic2ExpReactorPlanner#22]
Can I repost and localize your software in a Chinese Minecraft forum?

**Comment by MauveCloud** [comment]
Go ahead.  I've put the code under GPL licensing, which if I understand it correctly means you technically didn't need to ask.

Also see #13 - if you provide the translations, I can add them to the project and make a new release for them before you post a copy on the Chinese Minecraft forum you mention.

**Comment by MauveCloud** [comment]
Closed due to inactivity.
