### ISSUE TITLE
Condensator Simulation

### ISSUE THREAD

**Issue by Shananiganeer** [MauveCloud/Ic2ExpReactorPlanner#23]
Condensators are not being simulated properly. They currently function identically to Coolant Cells (heatsink with no other mechanics). They should instead behave as if they are being fed with redstone/lapis as appropriate. The simulation should also keep track of how much redstone/lapis is used per cycle.

**Comment by MauveCloud** [comment]
I don't think it's appropriate to _always_ simulate it that way, since some players may use this for reactor designs in 1.7.10, which does not have the Reactor Coolant Injector, or plan to skip using that block for other reasons.  However, I can look into adding an option to simulate the reactor as if it had a stocked RCI attached.

**Comment by Shananiganeer** [comment]
You can have the simulation tell the player how often they need to input redstone/lapis manually in addition to the total count. This way the presence of an RCI is irrelevant.

**Comment by MauveCloud** [comment]
To do that properly, I'd have to know _how_ the condensators are being managed - an RCI does it automatically but only allows blocks of redstone/lapis.  Without an RCI, the player has to do it at least somewhat manually (often including stopping the reactor to do so, which can influence its behavior, such as if the reactor had built up heat but has fans to dissipate it while switched off), but also has the option to use single pieces of redstone/lapis, which according to the IC2 Wiki page about the condensators is often more cost-efficient.

**Comment by Shananiganeer** [comment]
Whoops, forgot you had to actually pull the component out and craft it with the redstone/lapis. Had it in my head that you could right-click the redstone/lapis onto the component in the reactor GUI.

Option for RCI would be fantastic.

**Comment by MauveCloud** [comment]
Added in v2.1.6.
