### ISSUE TITLE
Heat output issue

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#26]
![problem1](https://user-images.githubusercontent.com/34199560/33521259-3b406ef6-d808-11e7-9d1f-d1610b831c27.png)
![problem2](https://user-images.githubusercontent.com/34199560/33521261-40c76280-d808-11e7-966d-4877253fd9f2.png)
The simulated HU output and actual HU output is not the same.
Using IC2 2.8.27-ex112

**Comment by MauveCloud** [comment]
This is a bug in IC2, misreporting the HU output:
https://bt.industrial-craft.net/view.php?id=2030
If I change the planner to match what that version of IC2 shows, it will no longer match what the 1.7.10 version of IC2 shows, so I would have to add some sort of option to let the user select which version of IC2 is in use, which I am very reluctant to do - I am trying to keep the planner as version-agnostic as possible.
