### ISSUE TITLE
Noob question

### ISSUE THREAD

**Issue by Wiebesu** [MauveCloud/Ic2ExpReactorPlanner#27]
Hey, I was wondering on how to actually run your program. I don't see any form of .exe

**Comment by MauveCloud** [comment]
It's a Java application (cross-platform).  If you have Java installed properly, you should be able to double-click the jar file.

**Comment by Wiebesu** [comment]
That's odd?
Program and files says Java 8 Update 151 (64-bit) is installed

Yet I still don't see any runnable .jar file....

Perhaps by manually assigning java to the .jar file. Which file is the program?

Thanks!

**Comment by MauveCloud** [comment]
Now that you mentioned that, it looks like I failed to actually upload the binary when I released v2.1.7.  Maybe I was half-asleep when I did that. 🤦‍♂️ 
It should be there now.
