### ISSUE TITLE
Incorrect simulation

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#29]
The reactor shown is a stable reactor, but the simulation shows that it isn't.
![error](https://user-images.githubusercontent.com/34199560/36716000-b855e1c8-1bd3-11e8-88a2-5a04a60c94bc.PNG)
![2018-02-27_15 30 51](https://user-images.githubusercontent.com/34199560/36716016-cacf87a0-1bd3-11e8-9079-356c3104f636.png)

**Comment by MauveCloud** [comment]
I think when thorium rods were originally added to GT5u, they produced 1/5th the energy and 1/2 the heat of uranium rods, but at least 2 years ago from what I can find in the GT5u github, they were changed to be 2/5 the energy and 1/4 the heat, so I'm surprised nobody told me about this sooner.

**Comment by MauveCloud** [comment]
Fixed in v2.1.8
