### ISSUE TITLE
Missing naquadah fuel rods for GT5u

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#32]
naquadah fuel rods are missing(added in 5.09.26)

**Comment by MauveCloud** [comment]
Added to simulator in v2.2, though I must admit I'm not entirely clear on what makes it attractive to use naquadah in a nuclear reactor instead of in a naquadah reactor or a fusion reactor.

**Comment by KrisBigK** [comment]
1.It has a durability of 100,000, so maintenance is less
2.it is a way to make naquadria out of enriched naquadah, otherwise you need to make using fusion, which is farely expensive:)
