### ISSUE TITLE
Removing reactor plating doesn't update the initial reactor heat

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#34]
1. put any plating into the slots
2. set the initial reactor heat to more than 10000
3. remove the plating
4. simulate
"Reactor will explode at 0 seconds." without any heat source.

**Comment by MauveCloud** [comment]
Looking at decompiled code, I think a pre-heated reactor could actually be detonated by removing reactor plating, even if it had no redstone signal connected or fuel rods left inside.  Please let me know what you think the planner should do in this situation.

**Comment by KrisBigK** [comment]
> I think a pre-heated reactor could actually be detonated by removing reactor plating, even if it had no redstone signal connected or fuel rods left inside.

Yes, it will explode. I tried that.

> Please let me know what you think the planner should do in this situation.

I think that is a fault in the planner itself. The reactor max temperature shouldn't be able to be set higher than the reactor heat capacity. Maybe an easter egg in this situation?

**Comment by MauveCloud** [comment]
> I think that is a fault in the planner itself. The reactor max temperature shouldn't be able to be set higher than the reactor heat capacity. Maybe an easter egg in this situation?

I'm not disputing that it's a fault in the planner, but I was hoping you'd have a more specific suggestion.  I don't follow what you mean by "easter egg".  I can think of several ways to handle this, and I'm not sure which is best:
1. Leave it as-is, making it the user's responsibility to deal with it (though I discovered that the up/down arrows fail when the value is out of range, so this is probably bad).
2. Clamp the value to the new maximum.
3. Maintain the approximate ratio of the value to maximum (e.g. if it had been 10500/11000 before, make it 9545 now).
4. Reset the initial heat to 0 if the value would become out of range.

**Comment by KrisBigK** [comment]
> I'm not disputing that it's a fault in the planner, but I was hoping you'd have a more specific suggestion. I don't follow what you mean by "easter egg". I can think of several ways to handle this, and I'm not sure which is best:
Leave it as-is, making it the user's responsibility to deal with it (though I discovered that the up/down arrows fail when the value is out of range, so this is probably bad).
Clamp the value to the new maximum.
Maintain the approximate ratio of the value to maximum (e.g. if it had been 10500/11000 before, make it 9545 now).
Reset the initial heat to 0 if the value would become out of range.

I would go with 2 and 3. The user should be able to choose how to deal with this, since I think both make sense.

**Comment by KrisBigK** [comment]
I have another idea. Instead of changing the number itself, the reactor temperature becomes red when this happens, like this
![image](https://user-images.githubusercontent.com/34199560/54746389-0098b280-4c07-11e9-9ca2-a7c2d4ee0e83.png)
and it shows a warning message when mouse is hovered on it saying something like "The reactor will explode immediately if started with this temperature".

**Comment by MauveCloud** [comment]
Changing the text color of a JSpinner is non-trivial, since the component actually rendering the text is buried in the implementation - I found https://stackoverflow.com/questions/13324987/jspinner-text-color when looking for how to do that.  However, Talonius's planner reduced the initial hull heat when platings were removed to make the prior value no longer safe, so I guess I can follow suit.
