### ISSUE TITLE
Way off heat generation

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#35]
`2300120C0A120D0C0A06230C0D0C0D0C0D14230C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C140C0D0C0D0C0D0C140D140C0A120D0C140D`
In this design, the `Max Heat Generated` is totally incorrect. 
`230000000000000000062300000000000000230000000000000000000000000000000000000000000000000000000000000000000000`
With the exact same fuel rod and reflector, it generates 672 heat.
Using 2.2.1 version of the planner.

**Comment by MauveCloud** [comment]
Sorry, but I have to disagree with you on this one.  Presuming you simulated a fluid reactor to get the different heat generation, that's actually correct, because MOX fuel doubles its heat output when the reactor temperature goes over 50%.

**Comment by KrisBigK** [comment]
My apologies, I forgot about that
