### ISSUE TITLE
Weird behavior in "Replacement Threshold"

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#37]
13(h2s0)00000000000000000000000000000000000000000C000C00000000000C0D0C0D0C00000000000C0B0C000000000000000000000000|fsn

When experimenting with the idea of venting heat with the reactor heat exchanger, I found a weird behavior. The design above is just the concept but it can show the problem.

1.Place a reactor heat exchanger with a threshold of 4500 (default)
2.Click on the corresponding "a" square and see that it shows a threshold of 4500
3.Change the threshold to 0 in the right side
4.Replace the current reactor heat exchanger
5.Click on the corresponding "a" square again and it changes into 0
6.Click on the corresponding "a" square again and it changes into 4500 again
[video.zip](https://github.com/MauveCloud/Ic2ExpReactorPlanner/files/2977873/video.zip)

**Comment by MauveCloud** [comment]
I investigated this, and it seems to be a case of imperfect usage of the informal lock variable I set up to prevent the code field from changing while the program was changing controls that could affect it (and unlike some Swing controls, JSpinners always trigger events when changed, whether the change was triggered by the user or by the program).  It's easier to see if you put the reactor heat exchanger near the lower right, but the "a" button was changing the reactor code (at step 6), even though it was only supposed to select the component for adjusting automation settings.

However, now that automation settings can be configured when placing components, an alternative fix is possible: I could make the automation tab just for viewing the current automation settings of a component, and changing them would require placing the component again with different automation settings chosen in the upper right panel.

**Comment by KrisBigK** [comment]
> I investigated this, and it seems to be a case of imperfect usage of the informal lock variable I set up to prevent the code field from changing while the program was changing controls that could affect it
... and changing them would require placing the component again with different automation settings chosen in the upper right panel.

Is it possible to fix it? The alternative fix has a problem that after replacing that component, further placement of other components will require that number to be changed again, which is avoidable if the problem is directly fixed.

**Comment by MauveCloud** [comment]
I'm not certain I follow your logic for rejecting my "alternative fix" idea, but I think I'll be able to fix it to behave as originally intended.

**Comment by MauveCloud** [comment]
:( Shame on me for not adequately testing the inclusion of automation details in the reactor code.  This was actually a bug in the code string parser, which I should be able to release a hotfix for after testing.

**Comment by MauveCloud** [comment]
Fixed in v2.3.0.1
