### ISSUE TITLE
[Suggestion] More flexible simulation styles

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#38]
Allow the user to choose the following:
- 1.how many cycles to run?
- 2.run it as a pulsed reactor?
- 3.automate replacing component?

Although the 3 simulation styles that it currently have can do all above except 1, I hope that by changing it in this way, more confusion could be avoided.

Also, I suggest that the version of the planner used to create the code is included in the code to make those changes compatible with the reactor code generated in different versions.

**Comment by MauveCloud** [comment]
Instead of "how many cycles", what about "maximum reactor ticks to simulate"?  That would have 3 advantages:
1. It would eliminate the complication of figuring out the intent of cycle count for a mixed-fuel reactor
2. It would allow stopping in the middle of one of the cycles (in case anyone wants that)
3. It would still be a valid way to define the duration for a fuel-less reactor.

Other than that, I actually like this idea a lot - it would allow me to unify the simulations into a single class that simply checks for these as options (as opposed to three distinct classes for the different simulation types)

**Comment by MauveCloud** [comment]
I have committed an implementation of this, but now there are so many controls near the text field for the reactor code that the component palette above is starting to get crowded out.  I might have to move the reactor config (e.g. EU reactor vs. Fluid reactor, initial reactor heat, use reactor coolant injectors, etc.) to a tab below.

**Comment by KrisBigK** [comment]
> Instead of "how many cycles", what about "maximum reactor ticks to simulate"?

That's an excellent idea!

>  I might have to move the reactor config (e.g. EU reactor vs. Fluid reactor, initial reactor heat, use reactor coolant injectors, etc.) to a tab below.

![image](https://user-images.githubusercontent.com/34199560/54693934-6d0da600-4b62-11e9-836e-d566cc5e4475.png)
What about this? Moving the reactor code down can make it to have more digits been seen.
(Apologies for my poor photo-editing skills)

**Comment by MauveCloud** [comment]
That's not a bad idea, but it doesn't eliminate the problem I'm referring to, which is limited vertical space for the controls related to reactor config in the middle right panel while still leaving room for the top right panel (the "component palette" as I'm tentatively calling it).  Right now, the default window size for the planner in Windows 10 comes out as 1095x753, which is not a big deal on my 1440p monitor, or most desktop monitors (which I'd presume are generally 1080p or larger), but I'm anticipating that some players may be using this on older or low-end laptops limited to 1366x768 screen size.
Here's a preview of what the latest (unreleased) build looks like in terms of layout:
![PlannerSizeDemo](https://user-images.githubusercontent.com/8942955/54697202-66dbe300-4aea-11e9-97c4-597fefbb28a1.png)

**Comment by KrisBigK** [comment]
Actually I moved the tabs down to make space for the code (if you haven't noticed), and I managed to squeeze it down into 838*556 with version 2.3.0.2, so there should be no big deal to use it on low resolution computers except that component textures on the right is a bit blurry.
![image](https://user-images.githubusercontent.com/34199560/54724547-92bc9e80-4ba6-11e9-89d7-8d291365edd1.png)
Also, do you consider putting the EU/fluid reactor choice and the initial reactor heat into the same line?
![image](https://user-images.githubusercontent.com/34199560/54724705-3908a400-4ba7-11e9-8a63-1bbcc2d359c1.png)
