### ISSUE TITLE
No response for about half a minute when simulating

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#42]
`0000000000000000000000000000000000000000000000000000000000000C000C00000000000C000C0D0C00000000000C000C000013(h2s0,a0)|ean`
I'm not certain if this only occurs on my computer, but after clicking "Simulate" with this design, the program doesn't respond to my mouse click anymore. Only about half way through it did respond once, and the simulation time displayed is about 10 times shorter than the actual time.

**Comment by MauveCloud** [comment]
It's not just your computer - I figured that out, it had queued up something like 50k string concatenation tasks 😵  on the event dispatch thread (for listing the times when the exchanger was replaced), and I came up with a more efficient alternative.
