### ISSUE TITLE
[Suggestion] Optional code compression

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#44]
Since I've seen screenshots of unreleased planner with code compression, I would like to have a option not to compress the reactor code. It is sometimes useful to directly see how the code is changed.

**Comment by MauveCloud** [comment]
Sorry, but I'm going to decline this - the old way of generating reactor codes was all over the place and didn't make it simple for me to add new details to it, so I'm not going to try to maintain both versions concurrently (though I am preserving the ability to decode the mixed hex/base36 codes).  Feel free to compare for yourself:
Old reactor code generation, 53 lines of Java code:
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/dcd0dabcaec7cf72ad64b080c823e7f00b73339d/src/Ic2ExpReactorPlanner/Reactor.java#L202-L254
New reactor code generation, 36 lines of Java code, even after adding storage of max simulation ticks (33 if I don't count the comment lines):
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/master/src/Ic2ExpReactorPlanner/Reactor.java#L531-L566

**Comment by KrisBigK** [comment]
> the old way of generating reactor codes was all over the place and didn't make it simple for me to add new details to it

Why do? Since it is a old way, you don't have to update it. And, the compressed code isn't compatible with older versions of your planner, which complicates things when going back to older versions to test things.

**Comment by MauveCloud** [comment]
Ah, I think I somewhat misunderstood your reasons for wanting this.  I had not realized you'd be okay with losing details when using the copied old-style codes.

**Comment by KrisBigK** [comment]
Both the code before 2.3 and the code generated between 2.3 and 2.3.0.2 are fine, because they can be used in earlier versions. I would like to see the code generated in 2.3.0.2 when not compressing the code.

**Comment by MauveCloud** [comment]
> I'm worried about the downward compatibility after adding compressed codes. That makes going back to older versions to test things impossible.

Coming back to this, I'm less certain this makes sense - if you want to test things between versions for comparison, you can generate the code in the older version and paste it into the newer version.

**Comment by KrisBigK** [comment]
It is much more likely to use the newest version of the planner, thus potential bugs are usually found in newer versions, and then generate the code in the older version? That needs to completely re-build the design.
