### ISSUE TITLE
Reactor code contains unused data

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#45]
![image](https://user-images.githubusercontent.com/34199560/54863991-dcfe7500-4d8a-11e9-8319-0e55106a1d09.png)
In this case, no pulse duration is needed in the code. The same for threshold. Those should be added to the code only if pulse/automation is selected. 
I took the screenshot using 2.3.0.2 version, and this is another reason why I want to keep the old style codes.

**Comment by MauveCloud** [comment]
Since you highlighted parts of the reactor code in the old version of the planner, it looks like you want them removed from old-style codes shown in the new version of the planner.  What happened to:

> Since it is a old way, you don't have to update it.

then?

**Comment by KrisBigK** [comment]
I am not sure if the reactor code in the newest version still contains that since it isn't visualized. In the old version however, I can see that straight away.
Whether or not to fix this is up to you. I don't think it is more complex than a few if statements.
