### ISSUE TITLE
Component icons don't resize automatically in certain conditions unlike those in the reactor grid

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#46]
Two demostrations:
![image](https://user-images.githubusercontent.com/34199560/54866198-f95ed980-4dab-11e9-91e5-39f484bb2c32.png)
![image](https://user-images.githubusercontent.com/34199560/54866212-14314e00-4dac-11e9-880f-95efd683f813.png)
This problem is automatically fixed when minimizing the window and re-opening it again.

Steps to reproduce:
For the first one:
1.vertically reduce the window size until it becomes a line
![image](https://user-images.githubusercontent.com/34199560/54866354-b1d94d00-4dad-11e9-80a1-266307285b46.png)
2.vertically increase the window size to a certain point when the icons become bigger and suddenly become small again.
For the second one: Just move up the line circled in the picture below
![image](https://user-images.githubusercontent.com/34199560/54866472-08935680-4daf-11e9-9d2f-86fcc4ba7b65.png)

**Comment by MauveCloud** [comment]
Evidently, I hadn't bothered to test this before, however, now that I did, I discovered you were mistaken about this part:

> unlike those in the reactor grid

Both only resized the existing images when the window was resized (not when the split panes were), though placing a new component in the grid would calculate an appropriate image size, which allowed me to get this effect:
![MultisizeComponents](https://user-images.githubusercontent.com/8942955/54871244-5a67bc80-4d6e-11e9-9ff9-9bb001c2ca2b.png)
