### ISSUE TITLE
[Suggestion] Align the simulation controls

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#49]
Left aligned
![image](https://user-images.githubusercontent.com/34199560/54875268-ae3dd880-4e36-11e9-8f1c-a9f17361faa0.png)
Center aligned
![image](https://user-images.githubusercontent.com/34199560/54875311-97e44c80-4e37-11e9-88c1-1c94bc0244b7.png)
I like the center aligned one more.

**Comment by MauveCloud** [comment]
I agree, center aligned looks better.
