### ISSUE TITLE
Missing Features

### ISSUE THREAD

**Issue by Chocohead** [MauveCloud/Ic2ExpReactorPlanner#5]
Compared to the old planner, yours doesn't show:
* Cooling effect of vents (actual + maximum)
* RSH/LZH Cooling (not that anyone actually uses those anymore but still :P)
* The heat generated from all the uranium per pulse
* The net gain/loss of heat per pulse
* Uranium efficiency (not that I remember that formula, but it'd be nice)
* Potential unused generation time is the redstone signal kicks in and the reactor could go further before exploding

That is just in order that I thought of them, priority wise I'd put the vent cooling, heat generated and net heat change as more important that the efficiency or unused generation time.

**Comment by MauveCloud** [comment]
Implemented in v1.3.
