### ISSUE TITLE
Overlapping buttons

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#52]
![0123](https://user-images.githubusercontent.com/34199560/55039329-b5472f80-505e-11e9-96f5-cfbfcab9d914.PNG)

This happens when the planner is opened, and automatically fixed by mouse hovering over the affected buttons .

**Comment by MauveCloud** [comment]
I am not currently able to reproduce this, which will make it more difficult to track down and fix:
![PlannerDefaultSize](https://user-images.githubusercontent.com/8942955/55041831-2ac5e800-4fec-11e9-8e99-df3f7c0b6c3c.png)
However, you seem to have ended up with buttons 2 pixels taller than on my system (at least the text buttons, like "Simulate", "Cancel", and "Paste Code").  I'm not sure what's causing that, but it might be related.

**Comment by KrisBigK** [comment]
[video.zip](https://github.com/MauveCloud/Ic2ExpReactorPlanner/files/3012525/video.zip)
It overlapped 6 px (counting the smallest distance between the buttons and the circle above) on my computer, and yours have 8 px of space between, so this doesn't show up on you.
