### ISSUE TITLE
Simulation outputs don't make sense in certain situations

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#55]
0000000000000000000000000000000000000000000000000C000000000300000C0D0C00000000000C0D0C0D0C00000000000C000C00|esn
![image](https://user-images.githubusercontent.com/34199560/55074867-6afc9780-50cc-11e9-91f3-b9fddf1640b0.png)
Why would it output 0 EU/t? I don't see any reason for that.

**Comment by MauveCloud** [comment]
> Why would it output 0 EU/t? I don't see any reason for that.

Comparing with decompiled IC2 code, I found some minor mistakes in the planner's internal logic regarding when to apply damage to the fuel rod (as well as how it checked for broken components, which was causing it to list a time of 20001 seconds for that fuel rod depletion, when it should have been 20000 seconds).
