### ISSUE TITLE
Conflicting heat output

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#57]
0000000000000000000000000000000000000000000000000C000000000300000C0D0C00000000000C0D0C0D0C00000000000C000C00|fsn
![image](https://user-images.githubusercontent.com/34199560/55075898-0b53bb80-50cf-11e9-8c05-275645d46070.png)

**Comment by MauveCloud** [comment]
How is this conflicting?  The first was checked right as the fuel rod depletes, the second after the simulation has confirmed that output has stopped.  Admittedly, after outputs have already been shown for the first situation, it might not make sense to show them again at the end of the simulation.

**Comment by KrisBigK** [comment]
> The first was checked right as the fuel rod depletes, the second after the simulation has confirmed that output has stopped.

Then you should specify that, because the only statement that I could find is "Total heat output before first fuel rod depleted". Maybe you can say "Simulation data when first fuel rod depletes" on the top.
