### ISSUE TITLE
[Suggestion] Show "HU" instead of "heat" when listing reactor outputs

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#58]
![1](https://user-images.githubusercontent.com/34199560/55076282-ff1c2e00-50cf-11e9-9eed-09c6e762f597.PNG)
I think that using "HU" in the places that I've highlighted above (and those below) is better than "heat", which might lead to confusion.

**Comment by MauveCloud** [comment]
I think that would be redundant with the units at the end.  What if it just said "Average output: (number) HU/t"? (admittedly, the EU outputs already have that redundancy, but I can change them as well)

**Comment by KrisBigK** [comment]
> What if it just said "Average output: (number) HU/t"?

Alright.
