### ISSUE TITLE
MOX fluid reactor simulation broken

### ISSUE THREAD

**Issue by lOmicronl** [MauveCloud/Ic2ExpReactorPlanner#6]
MOX fuel rods do not display the proper increase in heat output when placed in a fluid reactor and given an increased starting temperature.

Up to a value of 5000, nothing at all happens in the output data. The fuel rods still generate the same heat as they did at 0 hull heat, and cooling systems that should only be stable at 0 hull heat still report as stable. At any value of 5001 or higher, the heat output instead appears to be double the standard value. This value persists all the way up to 9999 heat, the highest possible to enter without causing an instant meltdown.

The MOX behavior of the EU reactor sim is correct, on the other hand; those fuel rods scale up their EU output and efficiency smoothly with every degree of temperature change. It's only the fluid reactor sim that's not scaling properly.

**Comment by MauveCloud** [comment]
I'm sorry, but I have to disagree with you about this being a bug with my planner.  IC2, even up to build 715, exhibits that same threshold for the heat output of mox rods in a fluid reactor.  I originally found out by looking at decompiled IC2 code, but now I've confirmed it in creative mode as well.
