### ISSUE TITLE
Incorrect hull heating calculation

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#63]
![image](https://user-images.githubusercontent.com/34199560/55162271-6e625280-51a2-11e9-86f2-27c44e17dc9f.png)
02230A120D0C0D110A03030C0D0C0D0C0D12020C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D0C0D110A110D0C0D110A11|fsn
In this case, why is the average value higher than the actual value? Only the fuel rods should be counted into hull heating.

**Comment by MauveCloud** [comment]
> Only the fuel rods should be counted into hull heating.

On the contrary.  Regular, advanced, and reactor heat exchangers can transfer heat both to and from the hull.  However, they don't "generate" their own heat, and aren't counted as part of the second number.

**Comment by KrisBigK** [comment]
It seems that you are counting its peaks again. Since two of the regular heat exchangers don't actually heat the hull (at least on average), hull heating from components is 8+8+4+4 = 24, and add that to 704 you get 729.

**Comment by MauveCloud** [comment]
> It seems that you are counting its peaks again.

Really?  I can't confirm that.  The relevant field is reset at the beginning of each reactor tick here:
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/fdef1cf101ca2f800265384921663d66b7574687/src/Ic2ExpReactorPlanner/components/ReactorItem.java#L149
Set for exchangers here:
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/fdef1cf101ca2f800265384921663d66b7574687/src/Ic2ExpReactorPlanner/components/Exchanger.java#L117
Accumulated during a simulation here:
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/fdef1cf101ca2f800265384921663d66b7574687/src/Ic2ExpReactorPlanner/AutomationSimulator.java#L618
And divided by the simulation time (minus the first 20 seconds, that were considered "warmup" to give components the opportunity to stabilize) for output here:
https://github.com/MauveCloud/Ic2ExpReactorPlanner/blob/fdef1cf101ca2f800265384921663d66b7574687/src/Ic2ExpReactorPlanner/AutomationSimulator.java#L644

Where am I "counting its peaks"?

Also, notice that "Hull cooling" is equivalent to "Hull heating" (at least within a margin of error of the displayed precision).  When exchangers cool the hull, they don't keep track of whether the hull temperature had been raised by themselves, other exchangers, or fuel rods.
