### ISSUE TITLE
Occasionally the components don't show up after pasting the code

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#66]
![image](https://user-images.githubusercontent.com/34199560/55271290-6ced7300-52e5-11e9-9242-396b839f9a68.png)
I promise I didn't edit this screenshot.

After this happens, clicking simulate returns the same results as if the code is empty.

**Comment by MauveCloud** [comment]
Weird question: was the code directly from earlier copying, or did you temporarily store it in a text editor or something before copying and pasting again?  Sometimes selecting the code will also pick up an extra whitespace at the end that is easy to miss, and the planner doesn't (yet) deal with this adequately.

**Comment by KrisBigK** [comment]
I tried to replicate this further and so far the codes that don't show up contain a whitespace in the end. Often this is caused by also copying a invisible newline character (which selects the entire line), and that shows up in the planner as a whitespace.

**Comment by MauveCloud** [comment]
I thought that might be what was happening, which means my recent commit should take care of it.  Since I haven't made a new release yet, I will mark this bug "fixed in dev" for now.
