### ISSUE TITLE
Incorrect reflector damage calculation

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#75]
erp=AudaVNFQXm4cSOhbi74BXOpjA/u39jCDqEPez+n+IEPrk3iw1eAL/e+o6d9E7LwB

![image](https://user-images.githubusercontent.com/34199560/63589229-29b8d700-c5db-11e9-9637-29bfd4a7c122.png)

The simulated results say that the reflectors will break at 5000 secs, but in-game testing showed that each reflector is taking damage at 4 per reactor tick, which works out to be 7500 sec. Same with thick reflectors.

**Comment by MauveCloud** [comment]
Actually, I looked closer - they don't all break at 5000 seconds - the top one does, but the side reflectors break at 10000 seconds, and the bottom one doesn't break.

**Comment by KrisBigK** [comment]
> the top one does, but the side reflectors break at 10000 seconds, and the bottom one doesn't break.

I ran the reactor full-cycle in-game and all 4 reflectors break at tick 7500. And the maximum reactor temperature should be 468, not 436 shown in the planner. For some time the hull temperature is 436 after starting it up, but it eventually increased.

![2019-08-24_08 45 28](https://user-images.githubusercontent.com/34199560/63630300-e9457180-c64b-11e9-9943-04e5ef75ebf4.png)
![2019-08-24_08 44 03](https://user-images.githubusercontent.com/34199560/63630302-eb0f3500-c64b-11e9-80ad-bf0af38619e9.png)

**Comment by MauveCloud** [comment]
Sorry, I meant that's what happens in the planner (when simulating).  I wasn't arguing about what happens in-game.  The core temperature looks like a separate issue, which might be more difficult to track down.

**Comment by MauveCloud** [comment]
Should be fixed in v2.4.
