### ISSUE TITLE
Possible issue with max reactor temperatue

### ISSUE THREAD

**Issue by MauveCloud** [MauveCloud/Ic2ExpReactorPlanner#78]
Design erp=AudaVNFQXm4cSOhbi74BXOpjA/u39jCDqEPez+n+IEPrk3iw1eAL/e+o6d9E7LwB

> The maximum reactor temperature should be 468, not 436 shown in the planner. For some time the hull temperature is 436 after starting it up, but it eventually increased.

![2019-08-24_08 44 03](https://user-images.githubusercontent.com/34199560/63630302-eb0f3500-c64b-11e9-80ad-bf0af38619e9.png)

_Originally posted by @KrisBigK in https://github.com/MauveCloud/Ic2ExpReactorPlanner/issues/75#issuecomment-524501472_

**Comment by MauveCloud** [comment]
@KrisBigK are you able to test whether this core temperature increase from 436 to 468 happens at a predictable time (e.g. based on reflector or fuel rod durability)?  If it doesn't, this could be a glitch or bug in IC2 or even Minecraft itself that is impractical to mimic in the planner.

**Comment by KrisBigK** [comment]
Seems that your planner is fine - after completely cooling down the heat exchangers in the bottom two rows before starting, the core temperature stayed at 436 until the reflectors broke. Only when the heat exchangers do not cool down completely do the core temperature go up to 468.
