### ISSUE TITLE
Codes without "erp=" prefix cannot be read

### ISSUE THREAD

**Issue by KrisBigK** [MauveCloud/Ic2ExpReactorPlanner#82]
The code in [this thread](https://forum.industrial-craft.net/thread/16020-all-heat-vents-and-exchangers-prompt-cannot-be-used-in-a-fluid-reactor-whats-wro/?postID=218506#post218506) doesn't work, but if I add the "erp=" prefix to the very beginning then it works.
In this case it would be great to automatically add the "erp=" prefix to the beginning.
![image](https://user-images.githubusercontent.com/34199560/86670086-d8fd7180-c026-11ea-8575-3a31c0091fda.png)
![image](https://user-images.githubusercontent.com/34199560/86670017-c7b46500-c026-11ea-84d4-af6ee24c6f04.png)

**Comment by MauveCloud** [comment]
Adding the "erp=" prefix automatically would interfere with handling of legacy Talonius planner codes, but if it doesn't fit the pattern of those and does fit that of a newer code with the "erp=" prefix stripped off, it will try to interpret it that way, as of v.2.4.
