### ISSUE TITLE
Resource Packs

### ISSUE THREAD

**Issue by Owy32** [MauveCloud/Ic2ExpReactorPlanner#84]
The resource pack feature doesnt work for me (have no other way to test)  even though the address is displayed but otherwise love the reactorplanner! BTW have tried moving the resource to same folder as ,jar and have restarted many times (not my pc, can do though) and it wont work.

**Comment by MauveCloud** [comment]
Yeah, looks like I missed a step in preliminary testing, and Java has an annoying discrepancy between extracting resources from a jar file that's running and extracting files from an external zip file - the former seems to require a leading slash, while the latter only works without it. :(
