### ISSUE TITLE
IC2 Classic Steam Reactor Support

### ISSUE THREAD

**Issue by Chocohead** [MauveCloud/Ic2ExpReactorPlanner#9]
IC2 Classic adds steam reactors which work different to the old steam setting by adding in special steam vents and a somewhat complex system to work out how much is produced based off how hot the vents are. Would you be interested in adding support for this? I suggested it to @Speiger but he said he doesn't have the Java knowledge to do it.

**Comment by MauveCloud** [comment]
Where can I find documentation for this steam reactor?

**Comment by Speiger** [comment]
@Chocohead @MauveCloud you can ask me.
A real documentation does not exsist but i can tell you everything on top of my head^^"
But not today i am tired and go to sleep now :3

**Comment by Speiger** [comment]
@MauveCloud how can i access you in a normal chat for information?

**Comment by MauveCloud** [comment]
Why do you need to?  If you're not willing to add a summary here (or in the IC2 forum thread about this project, or at least in a PM) of the mechanics of the steam vents, that leaves me unenthusiastic about adding support for them to my planner.

**Comment by Speiger** [comment]
@MauveCloud i did not say that i do not want to documentate everyhing...
I just did not have time to documentate it...
So that is not a problem. And why i want to chat with you the info is simply that you have it early and can progress on something which will be documentated anyway...

**Comment by MauveCloud** [comment]
I got the details from Speiger via PM, but several of the reactor components have different mechanics in IC2 Classic compared to IC2 Experimental, so I don't think it makes sense to handle them with the same planner.  Perhaps someone who's interested in and familiar with IC2 Classic can make a separate planner for the steam reactor.
